### ISSUE TITLE
Crash undefined is not an object (evaluating 's.View.propTypes.style'

### ISSUE THREAD

**Issue by herarya** [zbtang/React-Native-ViewPager#92]
Hi, after build release version
Crash undefined is not an object (evaluating 's.View.propTypes.style'
if debug mode is ok..

**Comment by ACOSW** [comment]
@herarya yep, it is known bug. We are all waiting for merge of this pull-request https://github.com/zbtang/React-Native-ViewPager/pull/90
Until it is not merged you can use this workaround:
- git clone https://github.com/rizzomichaelg/React-Native-ViewPager.git
- cd into cloned repo dir
- yarn link
- cd back to your project dir
- yarn link rn-viewpager

After this steps your project will use forked and fixed by @rizzomichaelg viewpager.

**Comment by ovr** [comment]
@ACOSW @herarya more easy way:

Update `package.json`:

```
"rn-viewpager": "rizzomichaelg/React-Native-ViewPager#38a78ae",
```

**Comment by punksta** [comment]
View.propTypes should not be accessed ever.

**Comment by punksta** [comment]
![image](https://user-images.githubusercontent.com/13404754/32005229-6ea144c0-b9ac-11e7-9de3-4558cd9b284d.png)

**Comment by punksta** [comment]
Issue will be fixed after this merge. https://github.com/zbtang/React-Native-ViewPager/pull/90

**Comment by herarya** [comment]
@ovr @punksta thanks
